# Generated by Django 5.2.9 on 2026-01-10 15:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('branch_type', models.CharField(choices=[('LAUNDRY', 'Laundry Service'), ('CARWASH', 'Car Wash'), ('KOS', 'Kos'), ('OTHER', 'Other Business')], default='LAUNDRY', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, help_text="Staff's WhatsApp number for transaction reporting", max_length=20, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False, help_text='If True, transactions from this staff auto-approve without owner verification')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('assigned_branch', models.ForeignKey(blank=True, help_text='Branch where this staff member works (null for owner)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='app.branch')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('branches', models.ManyToManyField(blank=True, help_text='Branches that use this category', related_name='categories', to='app.branch')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this transaction is verified (auto-verified if from verified staff)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('date', models.DateField(help_text='The actual date of transaction')),
                ('description', models.TextField(blank=True)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('QRIS', 'QRIS'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('is_valid', models.BooleanField(default=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp Bot'), ('EMAIL', 'Email Report'), ('MANUAL', 'Manual Entry by Owner')], max_length=20)),
                ('source_identifier', models.CharField(blank=True, help_text='WhatsApp phone number that sent the data', max_length=100)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('reported_by', models.ForeignKey(blank=True, help_text='Staff who reported this transaction via WhatsApp', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_reported', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp Bot'), ('EMAIL', 'Email Report'), ('MANUAL', 'Manual Entry by Owner')], max_length=20)),
                ('raw_payload', models.JSONField(help_text='The full JSON received from the webhook')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('SUCCESS', 'Successfully Parsed'), ('FAILED', 'Parsing Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_logs', to='app.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'branch'], name='app_transac_date_2f20e2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_verified', 'date'], name='app_transac_is_veri_b3c7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reported_by'], name='app_transac_reporte_2c4ce4_idx'),
        ),
    ]
