# Generated by Django 5.2.9 on 2026-01-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_unique_transaction_per_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_transaction_per_source',
        ),
    ]
