# Generated by Django 5.2.9 on 2026-01-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_unique_transaction_per_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of the sales summary')),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp Bot'), ('EMAIL', 'Email Report'), ('MANUAL', 'Manual Entry by Owner')], help_text='Email source: Luna or Hitachi', max_length=20)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qris_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('raw_data', models.JSONField(blank=True, help_text='Full parsed data from email (top products, categories, etc.)', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='app.branch')),
                ('ingestion_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='app.ingestionlog')),
            ],
            options={
                'verbose_name_plural': 'Daily Summaries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date', 'branch'], name='app_dailysu_date_e216fe_idx'), models.Index(fields=['source', 'date'], name='app_dailysu_source_7755d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('branch', 'date', 'source'), name='unique_daily_summary')],
            },
        ),
    ]
