# Generated by Django 5.2.9 on 2026-01-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_transaction_unique_transaction_per_source'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('branch', 'date', 'amount', 'transaction_type', 'category', 'source', 'source_identifier'), name='unique_transaction_per_source'),
        ),
    ]
